ci: add sonarcloud github workflow
nordcloud/mca-monitoring pull request #35
Opened 2022-10-14 08:17 UTC by martpet

2022-10-17 06:31 UTC, toorhamza requested changes

2022-10-17 06:31 UTC, toorhamza commented on .github/workflows/sonarcloud.yml
> +         -Dsonar.projectKey=iac-app-junaliikennointi-ravi
the project key needs to be updated here too

2022-10-17 06:35 UTC, jupekett requested changes

2022-10-17 06:35 UTC, jupekett commented on .github/workflows/sonarcloud.yml
> +         -Dsonar.projectKey=iac-app-junaliikennointi-ravi
Project key is wrong.

2022-10-24 10:39 UTC, toorhamza approved these changes
The project key was updated

2022-10-24 10:39 UTC, merged